---
- name: route-alerts-by-alertname
  hosts: localhost
  sources:
    - ansible.eda.webhook: {}

  rules:
    - name: handle HighCPU
      condition: event.alert.labels.alertname == "HighCPU"
      action:
        run_job_template:
          name: "Remediate-CPU"
          organization: "Default"
          job_args:
            extra_vars:
              alertname: "{{ event.alert.labels.alertname | default('N/A') }}"
              instance:  "{{ event.alert.labels.instance   | default('N/A') }}"
              severity:  "{{ event.alert.labels.severity   | default('N/A') }}"
              target_hosts: "{{ event.alert.labels.host | default('localhost') }}"

    - name: handle DiskFull
      condition: event.alert.labels.alertname == "DiskFull"
      action:
        run_job_template:
          name: "Remediate-Disk"
          organization: "Default"
          job_args:
            extra_vars:
              alertname: "{{ event.alert.labels.alertname | default('N/A') }}"
              instance:  "{{ event.alert.labels.instance   | default('N/A') }}"
              severity:  "{{ event.alert.labels.severity   | default('N/A') }}"
              target_hosts: "{{ event.alert.labels.host | default('localhost') }}"

    - name: catch-all for unknown alerts
      condition:  1 == 1
      action:
        debug:
          msg: >
            Unknown alert: {{ event.alert.labels.alertname | default('N/A') }}
            Full payload: {{ event }}

